version: '3'

services: 
  db: 
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_USER: homestead
      MYSQL_PASSWORD: homestead
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
    volumes:
      - mysql-data:/var/lib/mysql
    ports: 
      - 3306:3306

  phpmyadmin:
    depends_on: 
        - db
    image: phpmyadmin/phpmyadmin:5
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - 8081:80

  composer:
    image: composer:1.9.3
    command: install --ignore-platform-reqs
    volumes:
      - ./:/app

  laravel:
    depends_on:
      - db
      - composer
    image: hashman/apache2-php-fpm:7.2
    environment:
      DB_HOST: db
      DB_DATABASE: homestead
      DB_USERNAME: homestead
      DB_PASSWORD: homestead
    command: php artisan key:generate && php artisan migrate
    volumes:
      - "./:/code"
    ports:
      - 8080:80

  node:
    depends_on:
      - laravel
    build:
      context: ./
      dockerfile: frontEnd.Dockerfile
    volumes:
      - "./:/code"


volumes:
  mysql-data:
