# This is a basic workflow to help you get started with Actions

name: Test

on:
  push:
    branches: [ feature/test-action ]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Composer install
        uses: docker://composer:1.9.1
        with:
          args: install
      - name: Setup extension
        run: |
          docker-php-ext-install -j$(nproc) iconv intl xml soap opcache pdo pdo_mysql mysqli mbstring
          docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      - name: PHPUnit testing
        uses: docker://php:7.2
        with:
          args: php vendor/bin/phpunit
